name: CI

on:
  pull_request:
    branches:
     - "**"
  push:
    branches:
      - master

jobs:
  run-tests:
    name: python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ self-hosted ]
        tests_module: [ "cms", "common", "lms", "openedx" ]
    steps:
    - uses: actions/checkout@v2
    - name: Fetch master to compare coverage
      run: git fetch --depth=1 origin master

    - name: install requirements
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/edx/testing.txt

    - name: run tests
      env:
        TEST_MODULE: ${{ matrix.tests_module }}
      run: |
        ls -a
        pwd
        pytest $TEST_MODULE
